import "../globals.css";

import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Header from "./Header";
import localFont from "next/font/local";

const SVNgilroy = localFont({
  src: [
    {
      path: "../../assets/fonts/SVN-Gilroy Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy SemiBold.otf",
      weight: "600",
      style: "normal",
    },
  ],
});

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "vi" }];
}

export const metadata = {
  title: "Viettel Logistics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={SVNgilroy.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
