import "@assets/css/globals.scss";
import "@assets/css/theme.scss";
import "@assets/css/responsive.scss";
import "animate.css";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Header from "./components/Header";
import localFont from "next/font/local";

const SVNgilroy = localFont({
  src: [
    {
      path: "../../assets/fonts/SVN-Gilroy Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Viettel Logistics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={SVNgilroy.className}>
        {/* START LOADER  */}
        {/* <div id="loader-wrapper">
          <div id="loading-center-absolute">
            <div className="object" id="object_four"></div>
            <div className="object" id="object_three"></div>
            <div className="object" id="object_two"></div>
            <div className="object" id="object_one"></div>
          </div>
          <div className="loader-section section-left"></div>
          <div className="loader-section section-right"></div>
        </div> */}
        {/* END LOADER  */}
        <Header />
        {children}
      </body>
    </html>
  );
}
