import "@assets/css/globals.scss";
import "@assets/css/theme.scss";
import "@assets/css/responsive.scss";
import "@assets/css/animate.scss";
import { useLocale, useTranslations } from "next-intl";
import { notFound } from "next/navigation";
import Header from "./Header";
import localFont from "next/font/local";
import Loader from "./components/Loader";
import { ILocale, i18n } from "@configs/i18n";
import Footer from "./Footer";

const SVNgilroy = localFont({
  src: [
    {
      path: "../../assets/fonts/SVN-Gilroy Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../assets/fonts/SVN-Gilroy Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Viettel Logistics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  const t = useTranslations("home");
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={SVNgilroy.className}>
        <Loader />
        <Header
          titles={[
            t("home"),
            t("introduce"),
            t("service"),
            t("news"),
            t("recruitment"),
            t("contact"),
          ]}
        />
        {children}
        <Footer
          introduceTxt={t("about")}
          connectTxt={t("connect_with_us")}
          certifiedBy={t("certified_by")}
          locale={locale as ILocale}
        />
      </body>
    </html>
  );
}
